@checkNone
set nocompatible " Don't try to be vi compatible
syntax on " Turn on syntax highlighting

" Helps force plugins to load correctly when it is turned back on below
filetype off

set completeopt=noinsert,menuone,noselect

" For plugins to load correctly
filetype plugin indent on

" Pick a leader key
let mapleader = ","

" Search down into subfolders, tab-completion
set path+=**

" Security
set modelines=0

" Show line numbers
" set relativenumber
set number

" Blink cursor on error instead of beeping
set visualbell
set vb t_vb=

" Encoding
set encoding=utf-8

" Whitespace
set wrap
set textwidth=88
set formatoptions=tcqrn1
set tabstop=4
set shiftwidth=2
set softtabstop=4
set expandtab
set noshiftround

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Allow hidden buffers
set hidden

" Quick window switching
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-x> <C-w>x

" Rendering
set ttyfast

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

map <leader><space> :let @/=''<cr> " clear search
inoremap <CAPSLOCK> <ESC>
nmap <leader>t :NERDTreeToggle<CR>
nmap <leader>f :Files<CR>

" Visualize tabs and newlines
" Use your leader key + l to toggle on/off
set listchars=tab:▸\ ,eol:¬
map <leader>l :set list!<CR> " Toggle tabs and EOL

" Color scheme (terminal)
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1

" ==== Coc.nvim === "
" use <tab> for trigger completion and navigate to next complete item
" function! s:check_back_space() abort
"   let col = col('.') - 1
"   return !col || getline('.')[col - 1]  =~ '\s'
" endfunction
" 
" inoremap <silent><expr> <TAB>
"       \ pumvisible() ? "\<C-n>" :
"       \ <SID>check_back_space() ? "\<TAB>" :
"       \ coc#refresh()
" 
"Close preview window when completion is done.
" autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
" === coc.nvim === "
" nmap <silent> <leader>dd <Plug>(coc-definition)
" nmap <silent> <leader>dr <Plug>(coc-references)
" nmap <silent> <leader>dj <Plug>(coc-implementation)

" === Nerdtree shorcuts === "
"  <C-t> - Toggle NERDTree on/off
"  <leader>f - Opens current file location in NERDTree
