@checkNone
syntax on
set nocompatible
set number
set relativenumber
set encoding=utf-8
set completeopt=noinsert,menuone,noselect

let mapleader = ","

" Helps force plugins to load correctly when it is turned back on below
" filetype off
" For plugins to load correctly
" filetype plugin indent on
" set background=dark
" autocmd vimenter * ++nested colorscheme solarized8

" Search down into subfolders, tab-completion
set path+=**

" Security
set modelines=0

" Blink cursor on error instead of beeping
set noerrorbells
set vb t_vb=

" Whitespace
set hidden
set nowrap
set textwidth=80
set colorcolumn=80
set formatoptions=tcqrn1
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set noshiftround

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Quick window switching
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-x> <C-w>x

" Rendering
set ttyfast

set nobackup
set noswapfile
set undodir=~/.vim/undodir
set undofile

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Searching
nnoremap / /\v
vnoremap / /\v
set hlsearch
set incsearch
set ignorecase
set smartcase
set incsearch
set showmatch

map <leader><space> :let @/=''<cr> " clear search
inoremap <CAPSLOCK> <ESC>
nmap <leader>t :NERDTreeToggle<CR>
nmap <leader>f :Files<CR>

" Visualize tabs and newlines
" Use your leader key + l to toggle on/off
set listchars=tab:▸\ ,eol:¬
map <leader>l :set list!<CR> " Toggle tabs and EOL


" ==== Coc.nvim === "
" use <tab> for trigger completion and navigate to next complete item
 function! s:check_back_space() abort
   let col = col('.') - 1
   return !col || getline('.')[col - 1]  =~ '\s'
 endfunction
 
 inoremap <silent><expr> <TAB>
       \ pumvisible() ? "\<C-n>" :
       \ <SID>check_back_space() ? "\<TAB>" :
       \ coc#refresh()
 
"Close preview window when completion is done.
 autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
" === coc.nvim === "
 nmap <silent> <leader>dd <Plug>(coc-definition)
 nmap <silent> <leader>dr <Plug>(coc-references)
 nmap <silent> <leader>dj <Plug>(coc-implementation)
